apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jupyterlab
  name: jupyterlab
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jupyterlab
    spec:
      containers:
      - args:
        - start.sh
        - jupyter
        - lab
        - --NotebookApp.token=
        env:
        - name: GRANT_SUDO
          value: "yes"
        - name: NB_GID
          value: "100"
        - name: NB_UID
          value: "1000"
        image: jupyter/tensorflow-notebook:latest
        name: jupyterlab
        ports:
        - containerPort: 8888
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /home/jovyan/work
          name: jupyterlab-claim0
      restartPolicy: Always
      volumes:
      - name: jupyterlab-claim0
        persistentVolumeClaim:
          claimName: jupyterlab-claim0
status: {}
