proxy:
  secretToken: c055e0a58c5266611f38e0ccee53c6631de627f5e005035f827ada65848b7842
  service:
    type: NodePort

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

prePuller:
  hook:
    enabled: true

cull:
  enabled: false

auth:
  admin:
    users:
      - admin

singleuser:
  # Defines the default image
  image:
    name: jupyter/datascience-notebook
    tag: 2343e33dec46
  memory:
    limit: 1G
    guarantee: 1G
  profileList:
    - display_name: "S environment"
      description: "Memoy size is 1G"
      default: true
    - display_name: "M environment"
      description: "Memoy size is 2G"
      kubespawner_override:
        mem_limit: "2G"
        mem_guarantee: "2G"
    - display_name: "L environment"
      description: "Memoy size is 4G"
      kubespawner_override:
        mem_limit: "4G"
        mem_guarantee: "4G"
