proxy:
  secretToken: c055e0a58c5266611f38e0ccee53c6631de627f5e005035f827ada65848b7842
  service:
    type: NodePort

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

prePuller:
  hook:
    enabled: true

cull:
  enabled: false

auth:
  admin:
    users:
      - admin

singleuser:
  # Defines the default image
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  memory:
    limit: 0.5G
    guarantee: 0.5G
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
        memory:
          mem_limit: 1.5G
          mem_guarantee: 1.5G
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46
